### ISSUE TITLE
使用自定义的docker-compose启动，连接mysql报错

### ISSUE THREAD

**Issue by ipengyo** [dnsjia/luban#48]
**Describe the bug**

dev-luban     | 您正在使用config的默认值, 配置路径为etc/config.yaml
dev-luban     | 2022/10/27 - 03:47:25.088       INFO    C:/Users/Administrator/Documents/mycode/luban/common/init_table.go:58   register table success
dev-luban     | cannot parse configuration file: configuration file of server not found
dev-luban-db  | 2022-10-27T03:47:25.090155Z 8 [Note] Aborted connection 8 to db: 'luban' user: 'root' host: '172.20.0.3' (Got an error reading communication packets)
dev-luban exited with code 1
dev-luban     | 您正在使用config的默认值, 配置路径为etc/config.yaml
dev-luban     | 2022/10/27 - 03:47:27.623       INFO    C:/Users/Administrator/Documents/mycode/luban/common/init_table.go:58   register table success
dev-luban     | cannot parse configuration file: configuration file of server not found
dev-luban-db  | 2022-10-27T03:47:27.625066Z 9 [Note] Aborted connection 9 to db: 'luban' user: 'root' host: '172.20.0.3' (Got an error reading communication packets)

**To Reproduce**

使用自己自定义的 docker-compose

docker-compose.yml
```
version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: dev-luban-db
    restart: always
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --wait-timeout=28800
    volumes:
      - ./mysql22:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=luban
      # - MYSQL_USER=luban-db
      # - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
  luban:
    image: registry.cn-hangzhou.aliyuncs.com/dnsjia/luban:latest
    container_name: dev-luban
    privileged: true
    restart: always
    volumes:
      - ./etc:/data/luban/etc
    ports:
      # 如果80端口被占用可替换为其他端口，例如: - "8000:80"
      - "8011:80"
    #environment:
    depends_on:
      - db

```

执行docker-compose up 就报错 

dev-luban     |
dev-luban     | 7:M 27 Oct 03:47:24.391 # Server started, Redis version 3.2.12
dev-luban     | 7:M 27 Oct 03:47:24.391 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dev-luban     | 7:M 27 Oct 03:47:24.391 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
dev-luban     | 7:M 27 Oct 03:47:24.391 * The server is now ready to accept connections on port 6379
dev-luban     | 您正在使用config的默认值, 配置路径为etc/config.yaml
dev-luban     | 2022/10/27 - 03:47:25.088       INFO    C:/Users/Administrator/Documents/mycode/luban/common/init_table.go:58   register table success
dev-luban     | cannot parse configuration file: configuration file of server not found
dev-luban-db  | 2022-10-27T03:47:25.090155Z 8 [Note] Aborted connection 8 to db: 'luban' user: 'root' host: '172.20.0.3' (Got an error reading communication packets)
dev-luban exited with code 1
dev-luban     | 您正在使用config的默认值, 配置路径为etc/config.yaml
dev-luban     | 2022/10/27 - 03:47:27.623       INFO    C:/Users/Administrator/Documents/mycode/luban/common/init_table.go:58   register table success
dev-luban     | cannot parse configuration file: configuration file of server not found
dev-luban-db  | 2022-10-27T03:47:27.625066Z 9 [Note] Aborted connection 9 to db: 'luban' user: 'root' host: '172.20.0.3' (Got an error reading communication packets)
Gracefully stopping... (press Ctrl+C again to force)
Container dev-luban  Stopping
canceled
